export enum PermissionName {
  // ================= USER =================
  USER_VIEW = "USER_VIEW",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  // ================= ROLE =================
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_UPDATE = "ROLE_UPDATE",

  // ================= PERMISSION =================
  PERMISSION_VIEW = "PERMISSION_VIEW",
  PERMISSION_CREATE = "PERMISSION_CREATE",
  PERMISSION_DELETE = "PERMISSION_DELETE",
  PERMISSION_ASSIGN = "PERMISSION_ASSIGN",

  // ================= DEPARTMENT =================
  DEPARTMENT_VIEW = "DEPARTMENT_VIEW",
  DEPARTMENT_CREATE = "DEPARTMENT_CREATE",
  DEPARTMENT_UPDATE = "DEPARTMENT_UPDATE",
  DEPARTMENT_DELETE = "DEPARTMENT_DELETE",
  DEPARTMENT_ASSIGN_USER = "DEPARTMENT_ASSIGN_USER",

  // ================= AUDIT =================
  AUDIT_VIEW = "AUDIT_VIEW",
}